### ISSUE TITLE
UTF8 Token Name decoding

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/path-find-xapp#4]
In my `rwietsevLFg8XSmG3bEZzFein1g8RBqWDZ` account I have a token with UTF8 encoded name as per common XRPL non-3 char token name use. There's a decoding FN for that, you can copy/paste from here:

https://github.com/XRPL-Labs/XrplTxData/blob/main/src/ext-dependencies/utils.ts#L31

**Comment by Labiad19** [comment]
[stellar-export (2).csv](https://github.com/XRPL-Labs/path-find-xapp/files/7358191/stellar-export.2.csv)
